name: CI_ANDROID

on:
  push:

jobs:
  checktask:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache gradle
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run checks and build
        run: ./gradlew assembleDebug